terraform state rm azurerm_resource_group.cloud-shell-storage-westeuropeterraform state rm azurerm_resource_group.DefaultResourceGroup-SUKterraform state rm azurerm_resource_group.infabdm-sandboxterraform state rm azurerm_resource_group.NetworkWatcherRGterraform state rm azurerm_resource_group.puppetrepoterraform state rm azurerm_resource_group.rg-cloudera-galleryterraform state rm azurerm_resource_group.rg-dwp-cloudera-sbox-da-testterraform state rm azurerm_resource_group.rg-dwp-qlik-sbox-da-testterraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-at-testterraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-coreterraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-omsterraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-tfterraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-tfstateterraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-vmimages-uksterraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-vmimages-ukwterraform state rm azurerm_resource_group.rg-dwp-win-sbox-da-testterraform state rm azurerm_resource_group.rg-Images-uksterraform state rm azurerm_resource_group.rg-Images-ukwterraform state rm azurerm_resource_group.rg-Images-weterraform state rm azurerm_resource_group.rg-packer-rh75-ukwterraform state rm azurerm_resource_group.testimagesterraform state rm azurerm_resource_group.testimages1terraform state rm azurerm_resource_group.cloud-shell-storage-westeurope
terraform state rm azurerm_resource_group.DefaultResourceGroup-SUK
terraform state rm azurerm_resource_group.infabdm-sandbox
terraform state rm azurerm_resource_group.NetworkWatcherRG
terraform state rm azurerm_resource_group.puppetrepo
terraform state rm azurerm_resource_group.rg-cloudera-gallery
terraform state rm azurerm_resource_group.rg-dwp-cloudera-sbox-da-test
terraform state rm azurerm_resource_group.rg-dwp-qlik-sbox-da-test
terraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-at-test
terraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-core
terraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-oms
terraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-tf
terraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-tfstate
terraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-vmimages-uks
terraform state rm azurerm_resource_group.rg-dwp-sbox-da-ach-vmimages-ukw
terraform state rm azurerm_resource_group.rg-dwp-win-sbox-da-test
terraform state rm azurerm_resource_group.rg-Images-uks
terraform state rm azurerm_resource_group.rg-Images-ukw
terraform state rm azurerm_resource_group.rg-Images-we
terraform state rm azurerm_resource_group.rg-packer-rh75-ukw
terraform state rm azurerm_resource_group.testimages
terraform state rm azurerm_resource_group.testimages1
