#!/usr/bin/python2
#from azure.common.client_factory import get_client_from_cli_profile
#from azure.mgmt.compute import ComputeManagementClient
#from azure.mgmt.resource import ResourceManagementClient
import subprocess
import requests
import adal
import os
import json
import sys
import glob
import argparse

scwd=os.getcwd()
print scwd
head, tail = os.path.split(scwd)
os.chdir(head)
cwd=os.getcwd()
head, tail = os.path.split(cwd)
newd=head+"/scripts"
os.chdir(newd)
print os.getcwd()

import azurerm_route_table
import azurerm_application_security_group
import azurerm_network_security_group
import azurerm_virtual_network
import azurerm_subnet
import azurerm_virtual_network_peering
import azurerm_managed_disk
import azurerm_storage_account
import azurerm_public_ip
import azurerm_key_vault

os.chdir(scwd)
print os.getcwd()


parser = argparse.ArgumentParser(description='terraform sub rg')
parser.add_argument('-s', help='Subscription Id')
parser.add_argument('-g', help='Resource Group')
parser.add_argument('-r', help='Filter azurerm resource')
parser.add_argument('-d', help='Debug')
args = parser.parse_args()
csub=args.s
crg=args.g
crf=args.r
deb=args.d
cde=False
az2tfmess="# File generated by az2tf see: https://github.com/andyt530/az2tf \n"


if csub is not None:
    print("sub=" + csub) 
    # validate sub
if crg is not None:
    print("resource group=" + crg)
    # validate rg
if crf is not None:
    print("resource filter=" + crf)
    # validate rg
if deb is not None:
    cde=True

if sys.version_info[0] > 2:
    #raise Exception("Must be using Python 2")
    print("Python version ", sys.version_info[0], " version 2 required, Exiting")
    exit()

def printf(format, *values):
    print(format % values )

#with open(filename, 'w') as f:
    #print >> f, 'Filename:'


#tenant = os.environ['TENANT']
#authority_url = 'https://login.microsoftonline.com/' + tenant
#client_id = os.environ['CLIENTID']
#client_secret = os.environ['CLIENTSECRET']
#resource = 'https://management.azure.com/'
#context = adal.AuthenticationContext(authority_url)
#token = context.acquire_token_with_client_credentials(resource, client_id, client_secret)
#headers = {'Authorization': 'Bearer ' + token['accessToken'], 'Content-Type': 'application/json'}
#params = {'api-version': '2016-06-01'}
#url = 'https://management.azure.com/' + 'subscriptions'
#r = requests.get(url, headers=headers, params=params)
#print(json.dumps(r.json(), indent=4, separators=(',', ': ')))
print "Access Token"
p = subprocess.Popen('az account get-access-token -o json', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
c=0
for line in p.stdout.readlines():
    if "accessToken" in line:
        tk=line.split(":")[1].strip(' ",')
        tk2=tk.replace(",", "")
        bt2=tk2.replace('"', '')
    if "subscription" in line:
        tk=line.split(":")[1].strip(' ",')
        tk2=tk.replace(",", "")
        sub2=tk2.replace('"', '')
retval = p.wait()
if csub is not None:
    sub=csub
else:
    sub=sub2.rstrip('\n')

bt=bt2.rstrip('\n')
print "Subscription:",sub
headers = {'Authorization': 'Bearer ' + bt, 'Content-Type': 'application/json'}


# subscription check
#https://management.azure.com/subscriptions?api-version=2014-04-01
print "REST Subscriptions ",
url="https://management.azure.com/subscriptions"
params = {'api-version': '2014-04-01'}
try: 
    r = requests.get(url, headers=headers, params=params)
    subs= r.json()["value"]
except KeyError:
    print "Error getting subscription list"
    exit("ErrorGettingSubscriptionList")
ssubs=json.dumps(subs)
if sub not in ssubs: 
    print "Could not find subscription with ID (Test 1) " + sub + " Exiting ..." 
    exit("ErrorInvalidSubscriptionID-1")

FoundSub=False
count=len(sub)
print count
for i in range(0, count):
    id=str(subs[i]["subscriptionId"])
    #print id + " " + sub
    if id == sub:
        FoundSub=True

if not FoundSub:
    print "Could not find subscription with ID (Test 2) " + sub + " Exiting ..." 
    #exit("ErrorInvalidSubscriptionID-2")


print "Found subscription " + sub + " proceeding ..."

if crg is not None:
    FoundRg=False
    # get and check Resource group
    url="https://management.azure.com/subscriptions/" + sub + "/resourceGroups"
    params = {'api-version': '2014-04-01'}
    r = requests.get(url, headers=headers, params=params)
    rgs= r.json()["value"]

    count=len(rgs)
    for j in range(0, count):    
        name=rgs[j]["name"]
        if crg.lower() == name.lower():
            print "Found Resource Group" + crg
            FoundRg=True

    if not FoundRg:
        print "Could not find Resource Group " + crg + " in subscription " + sub + " Exiting ..." 
        exit("ErrorInvalidResourceGroup")


print "REST Resources ",
fresfilename="data.json"
fres=open(fresfilename, 'w')
url="https://management.azure.com/subscriptions/" + sub + "/resources"
params = {'api-version': '2018-11-01'}
try: 
    r = requests.get(url, headers=headers, params=params)
    res= r.json()["value"]
except KeyError:
    print "Error getting resources"
    exit()
fres.write(json.dumps(res, indent=4, separators=(',', ': ')))
fres.close()


rfilename="resources2.txt"
fr=open(rfilename, 'w')
nprfilename="noprovider2.txt"
np=open(nprfilename, 'w')


count=len(res)
print count
for j in range(0, count):
    t1=res[j]
    name=res[j]['name']
    id=res[j]['id']
    rg1=id.split("/")[4]
    try:
        isext=id.split("/")[9]
    except IndexError:
        isext=""

    loc=res[j]['location']
    rtype=res[j]['type']
    rg=rg1.replace(".","-")
    #print rtype

    if rtype == "Microsoft.Compute/availabilitySets":
        prov="azurerm_availability_set"
        fr.write(rg + ":" + prov + "\n")
    elif rtype == "Microsoft.Network/networkSecurityGroups":
        prov="azurerm_network_security_group"
        fr.write(rg + ":" + prov + "\n")

    elif rtype == "Microsoft.Storage/storageAccounts": 
        prov="azurerm_storage_account"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_storage_share"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_storage_container"
        fr.write(rg + ":" + prov + "\n")

    elif rtype == "Microsoft.Network/networkSecurityGroups":
        prov="azurerm_network_security_group"
        fr.write(rg + ":" + prov + "\n")

    elif rtype == "Microsoft.Compute/virtualMachines": 
        #echo $isext
        if isext != "extensions":
            prov="azurerm_virtual_machine"
            fr.write(rg + ":" + prov + "\n")
                
    elif rtype == "Microsoft.Network/networkInterfaces": 
        prov="azurerm_network_interface"
        fr.write(rg + ":" + prov + "\n")
    
    elif rtype == "Microsoft.Compute/disks":
        prov="azurerm_managed_disk"
        fr.write(rg + ":" + prov + "\n")
        
    elif rtype == "Microsoft.Automation/automationAccounts": 
        prov="azurerm_automation_account"
        fr.write(rg + ":" + prov + "\n")
          
    elif rtype == "Microsoft.Network/virtualNetworks":
        prov="azurerm_virtual_network"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_subnet"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_virtual_network_peering"
        fr.write(rg + ":" + prov + "\n")

    elif rtype == "Microsoft.Network/publicIPAddresses":
        prov="azurerm_public_ip"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/loadBalancers":
        prov="azurerm_lb"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_lb_nat_rule"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_lb_nat_pool"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_lb_backend_address_pool"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_lb_probe"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_lb_rule"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/virtualNetworkGateways":
        prov="azurerm_virtual_network_gateway"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/connections":
        prov="azurerm_virtual_network_gateway_connection"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/routeTables": 
        prov="azurerm_route_table"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.OperationalInsights/workspaces":
        prov="azurerm_log_analytics_workspace"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype ==  "Microsoft.OperationsManagement/solutions":
        prov="azurerm_log_analytics_solution"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.KeyVault/vaults":
        prov="azurerm_key_vault"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_key_vault_secret"
        fr.write(rg + ":" + prov + "\n")

    elif rtype == "Microsoft.RecoveryServices/vaults":
        prov="azurerm_recovery_services_vault"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.ContainerRegistry/registries":
        prov="azurerm_container_registry"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.ContainerService/managedClusters":
        prov="azurerm_kubernetes_cluster"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/localNetworkGateways":
        prov="azurerm_local_network_gateway"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/expressRouteCircuits":
        prov="azurerm_express_route_circuit"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_express_route_circuit_authorization"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_express_route_circuit_peering"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Compute/images": 
        prov="azurerm_image"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/networkWatchers": 
        prov="azurerm_network_watcher"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/applicationSecurityGroups":
        prov="azurerm_application_security_group"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.ContainerInstance/containerGroups":
        prov="azurerm_container_group"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/applicationGateways": 
        prov="azurerm_application_gateway"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.DocumentDb/databaseAccounts":
        prov="azurerm_cosmosdb_account"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.ServiceBus/namespaces": 
        prov="azurerm_servicebus_namespace"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_servicebus_queue"
        fr.write(rg + ":" + prov + "\n")
                  
    elif rtype == "Microsoft.Network/trafficmanagerprofiles":
        prov="azurerm_traffic_manager_profile"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_traffic_manager_endpoint"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Web/serverFarms": 
        prov="azurerm_app_service_plan"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Web/sites": 
        prov="azurerm_app_service"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_function_app"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Compute/virtualMachineScaleSets":
        prov="azurerm_virtual_machine_scale_set"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.ManagedIdentity/userAssignedIdentities":
        prov="azurerm_user_assigned_identity"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Compute/snapshots":
        prov="azurerm_snapshot"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Databricks/workspaces":
        prov="azurerm_databricks_workspace"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Sql/servers": 
        prov="azurerm_sql_server"
        fr.write(rg + ":" + prov + "\n")
        prov="azurerm_sql_database"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype == "Microsoft.Network/dnszones": 
        prov="azurerm_dns_zone"
        fr.write(rg + ":" + prov + "\n")
            
    elif rtype ==  "microsoft.insights/autoscalesettings":
        prov="azurerm_monitor_autoscale_setting"
        fr.write(rg + ":" + prov + "\n")
            
    else:
        np.write(rtype + "\n")

fr.close()
np.close()

print "Optimizing Resources ..."
# sort unique and filter for Resource Group
rfilename="resources.txt"
fr=open(rfilename, 'w')
with open('resources2.txt', 'r') as r:
    for line in sorted(set(r)):
        trg=line.split(":")[0]
        trt=line.split(":")[1]
        #print trt
        if crg is not None:   # Resource Group Filter
            if trg == crg :
                if crf is not None:   # Resource Filter
                    if crf in trt:
                        fr.write(line,)
                else:
                    fr.write(line,)
        else:
            if crf is not None:   # Resource Filter
                if crf in trt :
                    fr.write(line,)
            else:
                fr.write(line,)
r.close()
fr.close()


if crf is None:
    crf="azurerm"


# sort unique and fileter for Resource Group
rfilename="noprovider.txt"
fr=open(rfilename, 'w')
with open('noprovider2.txt', 'r') as r:
    for line in sorted(set(r)):
        fr.write(line,)

r.close()
fr.close()
if os.path.exists("tf-staterm.sh"):
    os.remove('tf-staterm.sh')
if os.path.exists("tf-stateimp.sh"):
    os.remove('tf-stateimp.sh')



#
# handle resource groups
#

tfp="azurerm_resource_group"
print tfp,
tfrmf="001-"+tfp+"-staterm.sh"
tfimf="001-"+tfp+"-stateimp.sh"
tfrm=open(tfrmf, 'a')
tfim=open(tfimf, 'a')
url="https://management.azure.com/subscriptions/" + sub + "/resourceGroups"
params = {'api-version': '2014-04-01'}
r = requests.get(url, headers=headers, params=params)
rgs= r.json()["value"]

#frgfilename=tfp+".json"
#frg=open(frgfilename, 'w')
#frg.write(json.dumps(rgs, indent=4, separators=(',', ': ')))
#frg.close()
if cde:
    print(json.dumps(rgs, indent=4, separators=(',', ': ')))

tffile=tfp+"*.tf"
#fileList = glob.glob(tffile) 
# Iterate over the list of filepaths & remove each file.
#for filePath in fileList:
#    try:
#        os.remove(filePath)
#    except:
#        print("Error while deleting file : ", filePath)

count=len(rgs)
print count
for j in range(0, count):
    
    name=rgs[j]["name"]
    rg=name
    loc=rgs[j]["location"]
    id=rgs[j]["id"]
    if crg is not None:
        if rg.lower() != crg.lower():
            continue
    
    rname=name.replace(".","-")
    prefix=tfp+"."+rname
    
    rfilename=prefix+".tf"
    fr=open(rfilename, 'w')
    fr.write("")
    fr.write('resource "' + tfp + '" "' + rname + '" {\n')
    fr.write('\t name = "' + name + '"\n')
    fr.write('\t location = "'+ loc + '"\n')
 

# tags block
    try:
        mtags=rgs[j]["tags"]
    except:
        mtags="{}"
    tcount=len(mtags)-1
    if tcount > 1 :
        fr.write('tags { \n')
        print tcount
        for key in mtags.keys():
            tval=mtags[key]
            fr.write('\t "' + key + '"="' + tval + '"\n')
        #print(json.dumps(mtags, indent=4, separators=(',', ': ')))
        fr.write('}\n')
    
    fr.write('}\n') 
    fr.close()  # close .tf file

    tfrm.write('terraform state rm '+tfp+'.'+rname + '\n')
    tfim.write('echo "importing ' + str(j) + ' of ' + str(count-1) + '"' + '\n')
    tfcomm='terraform import '+tfp+'.'+rname+' '+id+'\n'
    tfim.write(tfcomm)

# end for
tfrm.close()
tfim.close()
#end resource group

# management locks


tfp="azurerm_management_lock"
azr=""
if crf in tfp:
    p = subprocess.Popen('az lock list -o json', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output, errors = p.communicate()
    azr=json.loads(output)

    if cde:
        print(json.dumps(azr, indent=4, separators=(',', ': ')))

    tfrmf="002-"+tfp+"-staterm.sh"
    tfimf="002-"+tfp+"-stateimp.sh"
    tfrm=open(tfrmf, 'a')
    tfim=open(tfimf, 'a')
    print tfp,
    count=len(azr)
    print count
    for j in range(0, count):
        
        name=azr[j]["name"]
        #loc=azr[j]["location"]
        id=azr[j]["id"]
        rg=azr[j]["resourceGroup"]
        level=azr[j]["level"]
        notes=azr[j]["notes"]
        scope1=id.split("/Microsoft.Authorization")[0].rstrip("providers")
        scope=scope1.rstrip("/")


        if crg is not None:
            print "rgname=" + rg + " crg=" + crg
            if rg.lower() != crg.lower():
                continue  # back to for
        

        rname=name.replace(".","-")
        prefix=tfp+"."+rg+'__'+rname
        #print prefix
        rfilename=prefix+".tf"
        fr=open(rfilename, 'w')
        fr.write("")
        fr.write('resource ' + tfp + ' ' + rg + '__' + rname + ' {\n')
        fr.write('\t name = "' + name + '"\n')
        #fr.write('\t location = "'+ loc + '"\n')
        fr.write('\t lock_level = "'+ level + '"\n')   
        fr.write('\t notes = "'+ notes + '"\n') 
        fr.write('\t scope = "'+ scope + '"\n')
    # tags block
        try:
            mtags=azr[j]["tags"]
        except:
            mtags="{}"
        tcount=len(mtags)-1
        if tcount > 1 :
            fr.write('tags { \n')
            print tcount
            for key in mtags.keys():
                tval=mtags[key]
                fr.write('\t "' + key + '"="' + tval + '"\n')
            #print(json.dumps(mtags, indent=4, separators=(',', ': ')))
            fr.write('}\n')
        
        fr.write('}\n') 
        fr.close()  # close .tf file

        tfrm.write('terraform state rm '+tfp+'.'+rg+'__'+rname + '\n')
        
        tfcomm='terraform import '+tfp+'.'+rg+'__'+rname+' '+id+'\n'
        tfim.write('echo "importing ' + str(j) + ' of ' + str(count-1) + '"' + '\n')
        tfim.write(tfcomm)  

    # end for
    tfrm.close()
    tfim.close()
    #end management locks

# 015 user assigned identity
tfp="azurerm_user_assigned_identity"
azr=""
if crf in tfp:
    p = subprocess.Popen('az identity list -o json', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output, errors = p.communicate()
    azr=json.loads(output)
    if cde:
        print(json.dumps(azr, indent=4, separators=(',', ': ')))

    tfrmf="015-"+tfp+"-staterm.sh"
    tfimf="015-"+tfp+"-stateimp.sh"
    tfrm=open(tfrmf, 'a')
    tfim=open(tfimf, 'a')
    print tfp,
    count=len(azr)
    print count
    for j in range(0, count):
        
        name=azr[j]["name"]
        loc=azr[j]["location"]
        id=azr[j]["id"]
        rg=azr[j]["resourceGroup"]

        if crg is not None:
            print "rgname=" + rg + " crg=" + crg
            if rg.lower() != crg.lower():
                continue  # back to for
        
        rname=name.replace(".","-")
        prefix=tfp+"."+rg+'__'+rname
        #print prefix
        rfilename=prefix+".tf"
        fr=open(rfilename, 'w')
        fr.write("")
        fr.write('resource ' + tfp + ' ' + rg + '__' + rname + ' {\n')
        fr.write('\t name = "' + name + '"\n')
        fr.write('\t location = "'+ loc + '"\n')
        fr.write('\t resource_group_name = "' + rg + '"\n')
    # tags block
        try:
            mtags=azr[j]["tags"]
        except:
            mtags="{}"
        tcount=len(mtags)-1
        if tcount > 1 :
            fr.write('tags { \n')
            print tcount
            for key in mtags.keys():
                tval=mtags[key]
                fr.write('\t "' + key + '"="' + tval + '"\n')
            #print(json.dumps(mtags, indent=4, separators=(',', ': ')))
            fr.write('}\n')
        
        fr.write('}\n') 
        fr.close()  # close .tf file

        tfrm.write('terraform state rm '+tfp+'.'+rg+'__'+rname + '\n')
        
        tfcomm='terraform import '+tfp+'.'+rg+'__'+rname+' '+id+'\n'
        tfim.write('echo "importing ' + str(j) + ' of ' + str(count-1) + '"' + '\n')
        tfim.write(tfcomm)  

    # end for
    tfrm.close()
    tfim.close()
    #end user assigned identity




#  020 ASG's
tfp="azurerm_availability_set"
azr=""
if crf in tfp:

    print "REST Avail Set"
    url="https://management.azure.com/subscriptions/" + sub + "/providers/Microsoft.Compute/availabilitySets"
    params = {'api-version': '2018-10-01'}
    r = requests.get(url, headers=headers, params=params)
    azr= r.json()["value"]
    if cde:
        print(json.dumps(azr, indent=4, separators=(',', ': ')))

    tfrmf="020-"+tfp+"-staterm.sh"
    tfimf="020-"+tfp+"-stateimp.sh"
    tfrm=open(tfrmf, 'a')
    tfim=open(tfimf, 'a')
    print tfp,
    count=len(azr)
    print count
    for i in range(0, count):

        name=azr[i]["name"]
        loc=azr[i]["location"]
        id=azr[i]["id"]
        #rg=azr[i]["resourceGroup"]
        rg=id.split("/")[4].replace(".","-")
        fd=str(azr[i]["properties"]["platformFaultDomainCount"])
        ud=str(azr[i]["properties"]["platformUpdateDomainCount"])
        #avm=azr[i]["virtualMachines"]
        skuname=azr[i]["sku"]["name"]
        rmtype="false"
        if "Aligned" in skuname:
            #print "skuname is true"
            rmtype="true"

        if crg is not None:
            if rg.lower() != crg.lower():
                continue  # back to for
        
        rname=name.replace(".","-")
        prefix=tfp+"."+rg+'__'+rname
        #print prefix
        rfilename=prefix+".tf"
        fr=open(rfilename, 'w')
        fr.write("")
        fr.write('resource ' + tfp + ' ' + rg + '__' + rname + ' {\n')
        fr.write('\t name = "' + name + '"\n')
        fr.write('\t location = "'+ loc + '"\n')
        fr.write('\t resource_group_name = "'+ rg + '"\n')   
        fr.write('\t platform_fault_domain_count = "' + fd + '"\n')
        fr.write('\t platform_update_domain_count = "' + ud + '"\n')
        fr.write('\t managed = "' + rmtype + '"\n')

    # tags block
        
        try:
            mtags=azr[i]["tags"]
            fr.write('tags { \n')
            for key in mtags.keys():
                tval=mtags[key]
                fr.write('\t "' + key + '"="' + tval + '"\n')
                #print tval
            #print(json.dumps(mtags, indent=4, separators=(',', ': ')))
            fr.write('}\n')
        except KeyError:
            pass
        
        fr.write('}\n') 
        fr.close()   # close .tf file

        tfrm.write('terraform state rm '+tfp+'.'+rg+'__'+rname + '\n')
            
        tfim.write('echo "importing ' + str(i) + ' of ' + str(count-1) + '"' + '\n')
        tfcomm='terraform import '+tfp+'.'+rg+'__'+rname+' '+id+'\n'
        tfim.write(tfcomm)  

    # end for i loop

    tfrm.close()
    tfim.close()
#end Avail Set







#  030 Route Table
azurerm_route_table.azurerm_route_table(crf,cde,crg,headers,requests,sub,json,az2tfmess)

# 040 ASG
azurerm_application_security_group.azurerm_application_security_group(crf,cde,crg,headers,requests,sub,json,az2tfmess)
#  050 NSG's
azurerm_network_security_group.azurerm_network_security_group(crf,cde,crg,headers,requests,sub,json,az2tfmess)
#  060 Virtual Networks
azr=azurerm_virtual_network.azurerm_virtual_network(crf,cde,crg,headers,requests,sub,json,az2tfmess)
#  070 subnets
azurerm_subnet.azurerm_subnet(crf,cde,crg,headers,requests,sub,json,az2tfmess,azr)
#  080 vnet peering
azurerm_virtual_network_peering.azurerm_virtual_network_peering(crf,cde,crg,headers,requests,sub,json,az2tfmess,azr)
# 090 Key Vault - using cli
azurerm_key_vault.azurerm_key_vault(crf,cde,crg,headers,requests,sub,json,az2tfmess,subprocess)
# 100 managed disk
azurerm_managed_disk.azurerm_managed_disk(crf,cde,crg,headers,requests,sub,json,az2tfmess)
#110 storgae account
azurerm_storage_account.azurerm_storage_account(crf,cde,crg,headers,requests,sub,json,az2tfmess)
#120 public ip
azurerm_public_ip.azurerm_public_ip(crf,cde,crg,headers,requests,sub,json,az2tfmess)



#  124 Traffic manager profile

tfp="azurerm_traffic_manager_profile"
azr=""
if crf in tfp:
# REST or cli
    print "REST Traffic Manager Profile"
    url="https://management.azure.com/subscriptions/" + sub + "/providers/Microsoft.Network/trafficmanagerprofiles"
    params = {'api-version': '2017-05-01'}
    r = requests.get(url, headers=headers, params=params)
    azr= r.json()["value"]
    if cde:
        print(json.dumps(azr, indent=4, separators=(',', ': ')))

    tfrmf="124-"+tfp+"-staterm.sh"
    tfimf="124-"+tfp+"-stateimp.sh"
    tfrm=open(tfrmf, 'a')
    tfim=open(tfimf, 'a')
    print tfp,
    count=len(azr)
    print count
    for i in range(0, count):

        name=azr[i]["name"]
        #loc=azr[i]["location"]
        id=azr[i]["id"]
        rg=id.split("/")[4].replace(".","-")

        if crg is not None:
            if rg.lower() != crg.lower():
                continue  # back to for
        
        rname=name.replace(".","-")
        prefix=tfp+"."+rg+'__'+rname
        #print prefix
        rfilename=prefix+".tf"
        fr=open(rfilename, 'w')
        fr.write(az2tfmess)
        fr.write('resource ' + tfp + ' ' + rg + '__' + rname + ' {\n')
        fr.write('\t name = "' + name + '"\n')
        #fr.write('\t location = "'+ loc + '"\n')
        fr.write('\t resource_group_name = "'+ rg + '"\n')

        trm=azr[i]["properties"]["trafficRoutingMethod"]
        fr.write('\t traffic_routing_method = "' +  trm + '"\n')
        ps=azr[i]["properties"]["profileStatus"]
        fr.write('\t profile_status = "' + ps + '"\n') 
      
        dnsc=azr[i]["properties"]["dnsConfig"]
        monc=azr[i]["properties"]["monitorConfig"]
                

# dns_config block

        rn=azr[i]["properties"]["dnsConfig"]["relativeName"]
        ttl=azr[i]["properties"]["dnsConfig"]["ttl"]
        
        if ttl == 0: 
            ttl=30
        
        fr.write('\t dns_config { \n')
        fr.write('\t\t relative_name = "' + rn + '"\n')
        #TF bug returning 0
        fr.write('\t\t ttl  = "' + str(ttl) + '"\n')
        fr.write('\t} \n')
        
# monitor_config block

        prot=azr[i]["properties"]["monitorConfig"]["protocol"]
        port=azr[i]["properties"]["monitorConfig"]["port"]

        fr.write('\t monitor_config { \n')
        fr.write('\t\t protocol = "' + prot + '"\n')
        fr.write('\t\t port  = "' + str(port) + '"\n')
        try:
            path=azr[i]["properties"]["monitorConfig"]["path"]
            fr.write('\t\t path  = "' + path + '"\n')
        except KeyError:
            pass
        fr.write('\t} \n')  
        


# tags block       
        try:
            mtags=azr[i]["tags"]
            fr.write('tags { \n')
            for key in mtags.keys():
                tval=mtags[key]
                fr.write('\t "' + key + '"="' + tval + '"\n')
            fr.write('}\n')
        except KeyError:
            pass

        fr.write('}\n') 
        fr.close()   # close .tf file

        if cde:
            with open(rfilename) as f: 
                print f.read()

        tfrm.write('terraform state rm '+tfp+'.'+rg+'__'+rname + '\n')

        tfim.write('echo "importing ' + str(i) + ' of ' + str(count-1) + '"' + '\n')
        tfcomm='terraform import '+tfp+'.'+rg+'__'+rname+' '+id+'\n'
        tfim.write(tfcomm)  

    # end for i loop

    tfrm.close()
    tfim.close()
#end traffic manager profile

#  125 traffic manager endpoint

tfp="azurerm_traffic_manager_endpoint"

if crf in tfp:
# REST or cli
# from above
    
    tfrmf="125-"+tfp+"-staterm.sh"
    tfimf="125-"+tfp+"-stateimp.sh"
    tfrm=open(tfrmf, 'a')
    tfim=open(tfimf, 'a')
    print tfp,
    count=len(azr)
    print count
    for i in range(0, count):

        #loc=azr[i]["location"]
        id=azr[i]["id"]
        pname=azr[i]["name"]
        azr2=azr[i]["properties"]["endpoints"]
        jcount=len(azr2)
        print "jcount=" + str(jcount)
        for j in range (0,jcount):

            name=azr2[j]["name"]
            id=azr2[j]["id"]
            rg=id.split("/")[4].replace(".","-")
            print rg
            print crg
            if crg is not None:
                if rg.lower() != crg.lower():
                    continue  # back to for
            
            rname=name.replace(".","-")
            prefix=tfp+"."+rg+'__'+rname
            print prefix
            rfilename=prefix+".tf"
            fr=open(rfilename, 'w')
            fr.write(az2tfmess)
            fr.write('resource ' + tfp + ' ' + rg + '__' + rname + ' {\n')
            fr.write('\t name = "' + name + '"\n')
            #fr.write('\t location = "'+ loc + '"\n')
            fr.write('\t resource_group_name = "'+ rg + '"\n')
            fr.write('\t profile_name = "' +  pname + '"\n')
            ttype=azr2[j]["type"].split("/")[2]
            fr.write('\t type = "' +  ttype + '"\n')
            print "hi2"
            pri=azr2[j]["properties"]["priority"]
            fr.write('\t priority = "' +  str(pri) + '"\n')
            wt=azr2[j]["properties"]["weight"]
            fr.write('\t weight = "' +  str(wt) + '"\n')

            tgt=azr2[j]["properties"]["target"]
            fr.write('\t target = "' +  tgt + '"\n')
            eps=azr2[j]["properties"]["endpointStatus"]
            fr.write('\t endpoint_status = "' +  eps + '"\n')
            try:
                tgtid=azr2[j]["properties"]["targetResourceId"]
                tgtrrg=azr2[j]["properties"]["targetResourceId"].split("/")[4].replace(".","-")
                tgtrid=azr2[j]["properties"]["targetResourceId"].split("/")[8].replace(".","-")          
                fr.write('\t target_resource_id = "${azurerm_public_ip.' + tgtrrg + '__' + tgtrid + '.id}"\n')
            except KeyError:
                pass


            fr.write('}\n') 
            fr.close()   # close .tf file

            if cde:
                with open(rfilename) as f: 
                    print f.read()

            tfrm.write('terraform state rm '+tfp+'.'+rg+'__'+rname + '\n')

            tfim.write('echo "importing ' + str(i) + ' of ' + str(count-1) + '"' + '\n')
            tfcomm='terraform import '+tfp+'.'+rg+'__'+rname+' '+id+'\n'
            tfim.write(tfcomm)  
        # end for j loop

    # end for i loop

    tfrm.close()
    tfim.close()
#end traffic manager endpoint

# ******************************************************************************************
exit()

#rclient = get_client_from_cli_profile(ResourceManagementClient)
#for resource_group in rclient.resource_groups.list():
#    print(resource_group.name)

# template

#############


